env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: .
plugins:
  - '@typescript-eslint'
  - import
  - prettier
rules:
  eqeqeq: error
  no-constant-condition: off
  "import/no-unresolved": error
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/ban-ts-comment": off
settings:
  "import/parsers": 
    "@typescript-eslint/parser": [".ts"]
  "import/resolver":
    typescript: {}
root: true
ignorePatterns: ["node_modules/", "dist/", "dist/**"]
